### ISSUE TITLE
您好，我测试过了。HDMI接口无法使用

### ISSUE THREAD

**Issue by SSFsystem** [T-Mach/Hackintosh-LENOVO-XIAOXIN700#1]
测试用的显示屏为koios27寸，测试效果是，如果不插HDMI线，屏幕正常显示。插上线后，电脑屏幕黑屏，koios屏幕闪烁几次后，出现桌面，但是桌面为灰色，不可加载状态。没有出现鼠标，拖动鼠标没有反应

**Comment by SSFsystem** [comment]
忘记说了，如果插入hdmi线后，再拔下hdmi线，电脑屏幕也是黑屏没有反应，只能重启

**Comment by SSFsystem** [comment]
经过查询，问题存在好像是因为新系统的这些机型，没有HDMI接口了，系统里就没有HDMI的驱动，所以输出会出问题，之前有人用工具改机型后，hdmi可以展示，但据它说10.4更新后就无法使用了

**Comment by SSFsystem** [comment]
发现1

**Comment by SSFsystem** [comment]
最后发现这个是可以使用的，只是内屏有时会黑屏。移动鼠标就可以使用了

**Comment by s6nqou** [comment]
我没有解决方案，最近换电脑了……
我电脑上的情况是：HDMI要开机之后再插，不然全黑屏，而且要开机之后睡眠唤醒一下再插，不然内屏黑屏
